# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cadb1311a7de8450babc95df56f9026ae13ef3b19c2200b6120c882dbe96fb2c22f959ba70ac9e89a2515d8f7b2dca1f5c22a73823728e92830b080adf52b08e

test:
  secret_key_base: 6cf957ae0fd0285ce6752a0a238622fb491378d3ad987012315328a41e714c10d17bea70c26961daa23cecb497e65f4c5668decde9efbd4856b93b07af052b93

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
